curl (7.50.1-1.1) unstable; urgency=medium
  * Rebase on debian/7.50.1-1

 -- Denis Bychkov <manover@gmail.com>  Wed, 03 Aug 2016 10:39:11 -0400

diff --git a/debian/curl-config b/debian/curl-config
--- a/debian/curl-config
+++ b/debian/curl-config
@@ -1,10 +1,10 @@
 #!/bin/sh
 
-CURLCONFIG="/usr/bin/$(dpkg-architecture -qDEB_HOST_GNU_TYPE)-curl-config"
+CURL_CONFIG="/usr/bin/$(dpkg-architecture -qDEB_HOST_GNU_TYPE)-curl-config"
 
-if [ -x "$CURLCONFIG" ]; then
-	exec "$CURLCONFIG" "$@"
+if [ -x "$CURL_CONFIG" ]; then
+	exec "$CURL_CONFIG" "$@"
 else
-	echo "$CURLCONFIG not found, try installing the package for $(dpkg-architecture -qDEB_HOST_ARCH) architecture"
+	echo "$CURL_CONFIG not found, try installing the package for $(dpkg-architecture -qDEB_HOST_ARCH) architecture" >&2
 	exit 1
 fi
